# DocSAF Configuration for CORD Dataset
# CORD: Consolidated Receipt Dataset

# Core parameters
alpha: 1.0
radius: 6.0

# Saliency computation
saliency: "gradcam"
saliency_target: "clip"

# Surrogate models
surrogates:
  - "openclip:ViT-L-14@336"

# OCR backend
ocr: "easyocr"

# Dataset-specific configuration
dataset:
  line_level: true
  is_normalize: false
  max_size: [1024, 1024]

# Training parameters - optimized for CORD
training:
  steps: 600
  batch_size: 16
  lr_alpha: 0.003
  lr_radius: 0.001
  tv_lambda: 3.0e-4

# EOT-light transforms - receipts are more robust to transformations
eot:
  eot_prob: 0.3
  jpeg_q_min: 50
  jpeg_q_max: 90
  resize_min: 0.9
  resize_max: 1.1

# Device and misc
device: "auto"
random_seed: 42
lpips_threshold: 0.06
