# DocSAF Configuration for CORD Dataset
# CORD: Consolidated Receipt Dataset

# Core parameters
alpha: 1.3
radius: 5

# Saliency computation
saliency: "gradcam"
saliency_target: "clip"

# Surrogate models
surrogates:
  - "openclip:ViT-L-14@336"

# OCR backend
ocr: "easyocr"

# Dataset-specific configuration
dataset:
  line_level: true
  is_normalize: false
  max_size: [1024, 1024]

# Training parameters - optimized for CORD
training:
  steps: 15000      # CORD has more training data
  batch_size: 16
  lr: 0.001      # Slightly lower LR for stability
  tv_lambda: 2.0e-3

# EOT-light transforms - receipts are more robust to transformations
eot:
  jpeg_q_min: 40
  jpeg_q_max: 95
  resize_min: 0.85
  resize_max: 1.15
  eot_prob: 0

# Device and misc
device: "auto"
random_seed: 42
lpips_threshold: 0.06
