# DocSAF Default Configuration
# Two primary tunable parameters only

# Core parameters (the two knobs)
alpha: 1.2         # attenuation field strength
radius: 7          # Gaussian kernel radius (px at ~300dpi)

# Saliency computation
saliency: "gradients"   # ["gradients", "gradcam"]
saliency_target: "clip" # CLIP text-image cosine similarity

# Surrogate models for ensemble attack
surrogates:
  - "openclip:ViT-L-14@336"
  # Note: BLIP-2 and Donut implementations need additional work
  # - "hf:blip2-opt-2.7b"
  # - "hf:naver-clova-ix/donut-base"

# OCR backend
ocr: "easyocr"   # ["easyocr", "paddleocr"]

# Training parameters
training:
  steps: 15000
  batch_size: 8
  lr: 0.01
  tv_lambda: 1.0e-3    # TV regularization weight (fixed)

# EOT-light transforms
eot:
  jpeg_q_min: 50
  jpeg_q_max: 90
  resize_min: 0.9
  resize_max: 1.1
  eot_prob: 0.5

# Device and misc
device: "auto"         # ["auto", "cuda", "cpu"]
random_seed: 42
lpips_threshold: 0.06  # perceptual distortion limit