# DocSAF Configuration for SROIE Dataset
# SROIE: Scanned Receipts OCR and Information Extraction

# Core parameters
alpha: 1.25
radius: 7.5

# Saliency computation
saliency: "gradients"
saliency_target: "clip"

# Surrogate models
surrogates:
  - "openclip:ViT-L-14@336"

# OCR backend
ocr: "easyocr"

# Dataset-specific configuration
dataset:
  line_level: true
  is_normalize: true
  max_size: [1024, 1024]

# Training parameters - optimized for SROIE
training:
  steps: 6000
  batch_size: 6
  lr: 0.01
  tv_lambda: 1.0e-3

# EOT-light transforms
eot:
  jpeg_q_min: 45
  jpeg_q_max: 90
  resize_min: 0.9
  resize_max: 1.1
  eot_prob: 0.4

# Device and misc
device: "auto"
random_seed: 42
lpips_threshold: 0.06
